HTTP/1.0 400 Bad Request
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
  <head><title>400 Bad Request</title></head>
  <body>
    <h1>400 Bad Request</h1>
    <p>Your request could not be understood by the server.</p>
  </body>
</html>